server:
  port: 8761

spring:
  application:
    name: registry

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
          defaultZone: http://registry:8761/eureka

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

management:
  security:
    enabled: false